### ISSUE TITLE
Add 'creation date' and 'author' fields to ChirunPackage

### ISSUE THREAD

**Issue by christianp** [chirun-ncl/chirun-lti#28]
It'd be nice to see these in the admin view. The creation date should be `auto_now_add`, so it's set when the package record is created, and author should be filled in from the course manifest once it's built, or from the config file before that.

**Comment by Lycanic** [comment]
Creation date already exists in the model, working on author at [author-28](/Lycanic/chirun-lti/tree/author-28)

- [x] Add to model 
- [x] Automatically fill on build
- [ ] Add creation date to admin
- [ ] Add author to admin

Is there a reasonable point at which to pull the author from the config before building? I believe the default is empty, how likely is it that someone would change the config and not build?

**Comment by christianp** [comment]
I think we should stick with just extracting info from the manifest after building, for now.
