### ISSUE TITLE
Firefox total-cookie-protection breaking chirun

### ISSUE THREAD

**Issue by Chriscrossing** [chirun-ncl/chirun-lti#3]
OS: OpenSUSE tumbleweed 20220527
Browser: Firefox
Firefox Ver: 100.0.2-1.1

Total cookie protection, which seems to be a relatively new feature on-top of firefox's standard privacy features, which is prompted to be enabled in a recent update (https://support.mozilla.org/en-US/kb/total-cookie-protection?as=u&utm_source=inproduct). This somehow interferes with chirun and it fails to launch. Disabling this feature in settings -> security -> then unchecking the box for "Test pilot our most powerful privacy feature ever" allows chirun to work again. 

The error message provided by chirun could do with catching this error and pointing the user to disabling this setting if there isn't a back-end solution.

**Comment by christianp** [comment]
I'm closing this as it only applies to the old version. The new version doesn't use cookies for authentication.
